spring:
  application:
    name: metric-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:nexus_metric_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:Assassin@s4u}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8082}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

# Nexus starter config
nexus:
  service-name: metric-service
  internal-token: ${INTERNAL_SERVICE_TOKEN:}